version: "3.7"

services:

  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8085:8088"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=myk6db

  grafana:
    image: bitnami/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin    # 관리자 아이디 설정
      - GF_SECURITY_ADMIN_PASSWORD=your_password   # 관리자 비밀번호 설정

  k6:
    image: grafana/k6
    container_name: k6
    # profiles:
    #   - k6-only
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
    entrypoint:
      - k6
      - run
      - --out
      - influxdb=http://influxdb:8086/myk6db
      - /scripts/script2-4.js
    depends_on:
      - influxdb
      - grafana

