kafka:
  clusters:
    -
      name: local
      bootstrapServers: kafka:29092
      schemaRegistry: http://kafka:8085
      schemaRegistryAuth:
        username: username
        password: password
#     schemaNameTemplate: "%s-value"
      # metrics:
      #   port: 9997
      #   type: JMX